In [1]:
#Importing necessary libraries for data analysis and visualization

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_churn = pd.read_csv("Churn_Modelling.csv")

In [4]:
df_churn.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
#removing unnecessary columns
df_churn = df_churn.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
df_churn.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
# Encoding categorical features
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# Gender (e.g., Female=0, Male=1)
df_churn['Gender'] = le.fit_transform(df_churn['Gender'])

# Geography (France=0, Germany=1, Spain=2)
df_churn['Geography'] = le.fit_transform(df_churn['Geography'])

df_churn.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,850,2,0,43,2,125510.82,1,1,1,79084.10,0

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


X = df_churn.drop('Exited', axis=1)


y = df_churn['Exited']

#Split: 80% for training the model, 20% for testing its performance
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Initializing logistic regression with max itteration = 5000 to ensure the model converges 
model = LogisticRegression(max_iter= 5000)
model.fit(X_train, y_train)

#Check accuracy
predictions = model.predict(X_test)
print(f"Churn Prediction Accuracy: {accuracy_score(y_test, predictions) * 100:.2f}%")

Churn Prediction Accuracy: 81.45%

C:\Users\SG\Documents\DataAnalysisCourse\New folder\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 5000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=5000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [12]:
# Evaluating the model accuracy on the test set
# The current model achieved an accuracy of approximately 81.45%.
predictions = model.predict(X_test)

importance = model.coef_[0]
feature_names = X.columns
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importance})


print(feature_importance_df.sort_values(by='Importance', ascending=False))
# Analyzing Feature Importance to understand which factors influence churn the most
# Positive values indicate factors that increase churn (like Age).
# Negative values indicate factors that help retain customers (like being an Active Member).

           Feature    Importance
1        Geography  9.974263e-02
3              Age  7.025404e-02
5          Balance  4.659909e-06
9  EstimatedSalary  2.455016e-07
0      CreditScore -9.252188e-04
4           Tenure -1.616039e-02
7        HasCrCard -6.244538e-02
6    NumOfProducts -6.810343e-02
2           Gender -4.027188e-01
8   IsActiveMember -1.066085e+00